# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
addons:
    apt:
        packages:
            - libnetcdf-dev
            - netcdf-bin
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
r_packages:
  - devtools
  - testthat
  - lucode2
install:
  - Rscript -e "for(pkg in c('devtools','testthat')) if(!requireNamespace(pkg)) install.packages(pkg)"
  - Rscript -e "if(!requireNamespace('rhdf5')){install.packages("BiocManager");BiocManager::install('rhdf5')}"
script:
  - Rscript -e 'devtools::test()'
